# Spring properties
spring:
  application:
     name: cmpl
  datasource:
    platform: h2
    url: jdbc:h2:file:./target/cmpl
  jpa:
    hibernate.ddl-auto: update
    database: H2
  logging:
    level:
      root: INFO
      org.springframework.web: ERROR
      org.hibernate: ERROR
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# HTTP Server
server:
  port: 3232  # HTTP (Tomcat) port
  